all:
	clear
	gcc test.c -lmenu -lncurses -o test
	./test
1:
	clear
	gcc test1.c -lncurses -o test
	./test
2:
	clear
	gcc test2.c -lncurses -o test
	./test
3:
	clear
	gcc test3.c -lncurses -o test
	./test


